modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/VazkiiMods/Neat"
license="MIT AND CC-BY-NC-SA-3.0"  # Code is MIT, assets are CC

[[mods]]
modId="neat"
displayName="Neat"
version="${version}"
authors="Vazkii"
description="Minimalistic Functional Unit Plates for the modern Minecrafter"

[[dependencies.neat]]
modId="forge"
mandatory=true
versionRange="[41.0.99,)"
