modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Vazkii/Neat"

[[mods]]
modId="neat"
displayName="Neat"
version="${version}"
authors="Vazkii"
description='''
Minimalistic Functional Unit Plates for the modern Minecrafter
'''
