name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Validate gradlew integrity
      uses: gradle/wrapper-validation-action@v1
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
    - name: Build with Gradle
      run: ./gradlew pmdMain spotlessJavaCheck build
    - name: PMD report
      uses: jwgmeligmeyling/pmd-github-action@v1
      if: failure()
      with:
        path: '**/reports/pmd/main.xml'
    - name: Stop Gradle
      run: |
        ./gradlew --stop
    - name: Calculate artifact names
      id: calculate_artifact_names
      run: |
        MC=$(awk -F '=' '/mc_version/ { print $2; }' gradle.properties)
        BUILD=$(awk -F '=' '/build_number/ { print $2; }' gradle.properties)
        echo "forge=Forge/build/libs/Neat-${MC}-${BUILD}-FORGE.jar" >> "$GITHUB_OUTPUT"
        echo "fabric=Fabric/build/libs/Neat-${MC}-${BUILD}-FABRIC.jar" >> "$GITHUB_OUTPUT"
    - name: Sign jars
      env:
        SIGNING_KEY: ${{ secrets.VIOLET_MOON_SIGNING_KEY }}
      if: ${{ env.SIGNING_KEY != '' }}
      run: |
        echo "${SIGNING_KEY}" | gpg --import -
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.forge }}
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.fabric }}
    - name: Archive Forge Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Forge
        path: |
          ${{ steps.calculate_artifact_names.outputs.forge }}
          ${{ steps.calculate_artifact_names.outputs.forge }}.asc
    - name: Archive Fabric Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fabric
        path: |
          ${{ steps.calculate_artifact_names.outputs.fabric }}
          ${{ steps.calculate_artifact_names.outputs.fabric }}.asc
    - name: Upload Releases
      if: startsWith(github.ref, 'refs/tags/release-')
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_REF: ${{ github.ref }}
        FABRIC_JAR: ${{ steps.calculate_artifact_names.outputs.fabric }}
        FORGE_JAR: ${{ steps.calculate_artifact_names.outputs.forge }}
        CURSEFORGE_TOKEN: ${{ secrets.VAZKII_CURSEFORGE_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.VAZKII_MODRINTH_TOKEN }}
      run: |
        scripts/upload_releases.sh
